#!/usr/bin/env bash

# need to put header "autogenerated..."

set -euxo pipefail

rm -f ../kyber.c ../kyber.h

rm -rf kyber

git clone https://github.com/pq-crystals/kyber kyber

pushd kyber
git checkout b628ba78711bc28327dc7d2d5c074a00f061884e
patch -p1 < ../0001-derandomize-ref.patch
popd

pushd kyber/ref

OUTFILE=../../../kyber.h

echo '/* DO NOT EDIT - THIS FILE WAS AUTOGENERATED */ ' >> $OUTFILE
echo "/* generated on" `date -u +"%Y-%m-%dT%H:%M:%SZ"` "        */" >> $OUTFILE
echo >> $OUTFILE
echo '/* single-file ref CRYSTALS-Kyber KEM        */' >> $OUTFILE
echo '/* source: https://github.com/oreparaz/kyber */' >> $OUTFILE

echo >> $OUTFILE
echo >> $OUTFILE


cat api.h >> $OUTFILE
cat params.h >> $OUTFILE
cat kem.h >> $OUTFILE
cat kex.h >> $OUTFILE

sed -i 's/#include "params.h"//g' $OUTFILE

OUTFILE=../../../kyber.c

echo '/* DO NOT EDIT - THIS FILE WAS AUTOGENERATED */ ' >> $OUTFILE
echo "/* generated on" `date -u +"%Y-%m-%dT%H:%M:%SZ"` "        */" >> $OUTFILE
echo >> $OUTFILE
echo '/* single-file ref CRYSTALS-Kyber KEM        */' >> $OUTFILE
echo '/* source: https://github.com/oreparaz/kyber */' >> $OUTFILE

echo >> $OUTFILE
echo >> $OUTFILE

SRC_HEADERS="poly.h polyvec.h indcpa.h reduce.h ntt.h cbd.h verify.h fips202.h symmetric.h"
SRC_KYBER="kem.c indcpa.c polyvec.c poly.c reduce.c ntt.c cbd.c verify.c symmetric-shake.c kex.c"
SRC_COMMON="fips202.c"

echo '#include "kyber.h"' >> $OUTFILE

for i in "$SRC_HEADERS"; do
    cat $i >> $OUTFILE
done

for i in "$SRC_COMMON"; do
    cat $i >> $OUTFILE
done

for i in "$SRC_KYBER"; do
    cat $i >> $OUTFILE
done

sed -i 's/#include "params.h"//g' $OUTFILE
sed -i 's/#include "polyvec.h"//g' $OUTFILE
sed -i 's/#include "poly.h"//g' $OUTFILE
sed -i 's/#include "fips202.h"//g' $OUTFILE
sed -i 's/#include "aes256ctr.h"//g' $OUTFILE
sed -i 's/#include "kem.h"//g' $OUTFILE
sed -i 's/#include "indcpa.h"//g' $OUTFILE
sed -i 's/#include "verify.h"//g' $OUTFILE
sed -i 's/#include "symmetric.h"//g' $OUTFILE
sed -i 's/#include "randombytes.h"//g' $OUTFILE
sed -i 's/#include "ntt.h"//g' $OUTFILE
sed -i 's/#include "reduce.h"//g' $OUTFILE
sed -i 's/#include "cbd.h"//g' $OUTFILE
sed -i 's/#include "kex.h"//g' $OUTFILE

popd

# test

rm -f kyber.o
rm -rf /tmp/test*
rm -rf /tmp/demo

#gcc -DKYBER_K=3 -fsanitize=address,undefined ../kyber.c kyber/ref/randombytes.c kyber/ref/test_kyber.c -o /tmp/test_kyber && /tmp/test_kyber
#gcc -DKYBER_K=3 -fsanitize=address,undefined ../kyber.c kyber/ref/randombytes.c kyber/ref/test_kex.c -o /tmp/test_kex && /tmp/test_kex
#gcc -DKYBER_K=3 -fsanitize=address,undefined ../kyber.c kyber/ref/randombytes.c kyber/ref/test_speed.c kyber/ref/cpucycles.c kyber/ref/speed_print.c  -o /tmp/test_speed && /tmp/test_speed
#gcc -DKYBER_K=3 -fsanitize=address,undefined ../kyber.c kyber/ref/randombytes.c ../demo.c -o /tmp/demo && /tmp/demo

gcc -DKYBER_K=3 ../kyber.c kyber/ref/randombytes.c kyber/ref/test_kyber.c -o /tmp/test_kyber && /tmp/test_kyber
gcc -DKYBER_K=3 ../kyber.c kyber/ref/randombytes.c kyber/ref/test_kex.c -o /tmp/test_kex && /tmp/test_kex
gcc -DKYBER_K=3 ../kyber.c kyber/ref/randombytes.c kyber/ref/test_speed.c kyber/ref/cpucycles.c kyber/ref/speed_print.c  -o /tmp/test_speed && /tmp/test_speed
gcc -DKYBER_K=3 ../kyber.c kyber/ref/randombytes.c ../demo.c -o /tmp/demo && /tmp/demo

rm -rf kyber