name: run in different architectures

on: [push, pull_request, workflow_dispatch]

jobs:
  test-many-architectures:
    runs-on: ubuntu-latest
    name: Test on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: s390x
            distro: ubuntu_latest
          - arch: aarch64
            distro: ubuntu_latest
          - arch: ppc64le
            distro: ubuntu_latest
          - arch: armv7
            distro: ubuntu_latest
          - arch: armv6
            distro: bullseye
          - arch: riscv64
            distro: ubuntu_latest
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@master
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          install: |
            apt-get update
            apt install -y build-essential git
          run: |
            cd script && ./amalgamate.sh